/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/ai-control/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List providers with masked key pool + counts */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ai-control/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider detail with masked key pool */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ai-control/providers/{providerId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Derived 5-state provider health snapshot */
        get: operations["getProviderHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ai-control/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logical model catalog (user sees provider count, not per-route cost) */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ai-control/models/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logical model detail (bindings incl. admin-only route params) */
        get: operations["getModel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ai-control/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Machine-readable capability registry for logical models */
        get: operations["listCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ai-control/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Estimated quote (provider cost admin-only; user projection strips it) */
        post: operations["quoteGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ai-control/internal/routing-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record + return an auditable routing decision */
        post: operations["recordRoutingDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Secret-free key metadata. Full api_key NEVER appears in any response. */
        MaskedKey: {
            id: string;
            provider_id: string;
            /** @example ••••1234 */
            masked: string;
            /**
             * @description sha256 前 12 hex（不可反推）
             * @example a1b2c3d4e5f6
             */
            fingerprint?: string;
            label?: string;
            enabled: boolean;
            /** @enum {string} */
            status?: "active" | "isolated" | "disabled";
            weight?: number;
            rpm?: number | null;
            concurrency?: number | null;
            /** @enum {string} */
            health?: "UNKNOWN" | "HEALTHY" | "DEGRADED" | "UNHEALTHY" | "DISABLED";
            /** Format: date-time */
            cooldown_until?: string | null;
            /** Format: date-time */
            last_used_at?: string | null;
            last_error_code?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string | null;
        };
        ProviderView: {
            id: string;
            name: string;
            type?: string;
            base_url?: string;
            protocol?: string;
            enabled: boolean;
            supported_types?: string[];
            capacity_model?: string;
            /** @description Legacy single-key fallback (masked). api_keys pool is the authority. */
            credential?: {
                has_legacy_key?: boolean;
                /** @example ••••abcd */
                masked_legacy_key?: string;
            };
            key_pool?: components["schemas"]["MaskedKey"][];
            key_pool_count?: number;
            active_key_count?: number;
        };
        ProviderHealth: {
            provider_id: string;
            /** @enum {string} */
            state: "UNKNOWN" | "HEALTHY" | "DEGRADED" | "UNHEALTHY" | "DISABLED";
            reasons?: string[];
            /** @enum {string|null} */
            circuit_state?: "CLOSED" | "OPEN" | "HALF_OPEN" | null;
            success_rate?: number | null;
            p95_latency_ms?: number | null;
            rate_limited?: boolean | null;
            key_availability?: number | null;
            consecutive_failures?: number;
            /** Format: date-time */
            updated_at?: string;
        };
        BindingView: {
            binding_id: string;
            provider_id: string;
            provider_model_code: string;
            enabled: boolean;
            priority?: number;
            weight?: number;
            legacy_fallback?: boolean;
            parameter_overrides?: {
                [key: string]: unknown;
            } | null;
            endpoint?: {
                [key: string]: unknown;
            } | null;
            base_url?: string | null;
        };
        LogicalModelView: {
            /** @description canonical 逻辑模型身份 */
            model_id: string;
            /** @description 仅 UI 展示，不参与路由 */
            display_name?: string;
            type: string;
            enabled?: boolean;
            capabilities: components["schemas"]["CapabilityDoc"];
            capability_version?: number;
            parameter_schema?: {
                [key: string]: unknown;
            };
            /** @description 平台积分价（用户可见） */
            credit_cost?: number | null;
            bindings: components["schemas"]["BindingView"][];
        };
        /** @description Machine-readable, versionable capability. Lives on the logical model; provider bindings can only NARROW (never extend). */
        CapabilityDoc: {
            /** @enum {string} */
            type: "text" | "text_to_image" | "image_to_image" | "image_edit" | "text_to_video" | "image_to_video" | "first_last_frame" | "reference_video" | "audio" | "tts";
            capabilities?: {
                [key: string]: boolean;
            };
            input_modalities?: ("text" | "image" | "video" | "audio")[];
            output_modalities?: ("text" | "image" | "video" | "audio")[];
            parameter_schema?: {
                [key: string]: unknown;
            };
            pricing_dimensions?: ("per_asset" | "per_1k_input_token" | "per_1k_output_token" | "per_second" | "per_char")[];
            version?: number;
        };
        QuoteRequest: {
            model_id: string;
            /** @default 1 */
            count: number;
            /** @description 可选：锁定逐线路成本估算 */
            binding_id?: string | null;
        };
        /** @description 完整报价（admin）；user projection 由服务端剥离 provider cost/margin。 */
        Quote: {
            /** @description admin-only */
            estimated_provider_cost?: number;
            estimated_platform_price?: number;
            estimated_credits?: number;
            /** @description admin-only */
            margin?: number;
            currency?: string;
            pricing_rule_id?: string | null;
            pricing_source?: string;
        };
        RoutingDecisionInput: {
            model_id: string;
            capability?: string | null;
            content_type?: string | null;
            region?: string | null;
            cost_preference?: string | null;
            latency_preference?: string | null;
            request_id?: string | null;
            generation_task_id?: string | null;
        };
        RoutingDecision: {
            /** @example rd-1a2b3c4d5e6f7890 */
            routing_decision_id: string;
            ts?: number;
            model_id: string;
            capability?: string | null;
            region?: string | null;
            selected: components["schemas"]["CandidateSummary"] | null;
            reason?: string;
            fallback_candidates: components["schemas"]["CandidateSummary"][];
            rejected: {
                bindingId?: string;
                modelId?: string;
                providerId?: string;
                rejectedAt?: string;
                reason?: string;
            }[];
            weights?: {
                [key: string]: unknown;
            } | null;
            seed?: number | null;
        };
        CandidateSummary: {
            bindingId: string;
            modelId?: string;
            providerId: string;
            score?: number | null;
            components?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: {
        /** @description No session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Providers (secret-free) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider (secret-free) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProviderHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderHealth"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logical models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogicalModelView"][];
                };
            };
        };
    };
    getModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logical model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogicalModelView"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityDoc"][];
                };
            };
        };
    };
    quoteGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequest"];
            };
        };
        responses: {
            /** @description Quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
        };
    };
    recordRoutingDecision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingDecisionInput"];
            };
        };
        responses: {
            /** @description Recorded decision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingDecision"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
