/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness + CPU shedding signal */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (DB/Redis up) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current session user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces the current user is a member of */
        get: operations["listWorkspaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects with pagination and filters */
        get: operations["listProjects"];
        put?: never;
        /** Create a new project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project detail and permissions */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update project metadata */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v2/projects/{projectId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a project */
        post: operations["archiveProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{projectId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an archived project */
        post: operations["restoreProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{projectId}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assets attached to a project (paginated, filterable) */
        get: operations["listProjectAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's assets (paginated, filterable) */
        get: operations["listMyAssets"];
        put?: never;
        /**
         * Provision a new durable asset into a project, or re-scope an existing asset
         * @description With `url` in the body a new media row is created (durable asset authority = media table). With `assetId` an existing media row owned by the caller is attached to the project. The Asset identity is the assetId (media.id) — never a provider temporary URL.
         */
        post: operations["createOrRegisterAsset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset detail with provenance summary */
        get: operations["getAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Liveness + CPU shedding signal. Real shape: /api/healthz */
        Health: {
            /** @example ok */
            status?: string;
            pg?: boolean;
            redis?: boolean;
            node_id?: string;
            uptime?: number;
            version?: string;
            ts?: number;
            /** @description compatibility alias for status=ok */
            ok?: boolean;
            cpu?: {
                percent?: number;
                shedding?: boolean;
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** @description Real shape: /api/readiness */
        Readiness: {
            /** @example ready */
            status?: string;
            pg?: boolean;
            redis?: boolean;
            node_id?: string;
            /** @description derived (status === 'ready'); kept for compat */
            ready?: boolean;
        } & {
            [key: string]: unknown;
        };
        MeResponse: {
            user?: components["schemas"]["User"] | null;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            displayName?: string;
            /** @enum {string} */
            role: "user" | "admin" | "system";
            credits?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        WorkspaceSummary: {
            id: string;
            name: string;
            ownerId: string;
            /** @enum {string} */
            role: "owner" | "member";
            /** @enum {string} */
            status: "active" | "suspended";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WorkspaceListResponse: {
            workspaces: components["schemas"]["WorkspaceSummary"][];
        };
        ProjectSummary: {
            id: string;
            workspaceId: string;
            ownerId: string;
            name: string;
            description?: string;
            /** @enum {string} */
            projectType: "general" | "studio" | "short_drama";
            /** @enum {string} */
            status: "draft" | "active" | "archived";
            coverAssetId?: string | null;
            version?: number;
            /** Format: date-time */
            archivedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectDetail: {
            project: components["schemas"]["ProjectSummary"];
            permissions: components["schemas"]["ProjectPermissions"];
        };
        ProjectListResponse: {
            projects: components["schemas"]["ProjectSummary"][];
            pagination: {
                limit: number;
                offset: number;
                total: number;
                hasMore: boolean;
            };
        };
        CreateProjectRequest: {
            workspaceId: string;
            name: string;
            description?: string;
            /**
             * @default general
             * @enum {string}
             */
            projectType: "general" | "studio" | "short_drama";
        };
        UpdateProjectRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            projectType?: "general" | "studio" | "short_drama";
            coverAssetId?: string | null;
        };
        ProjectPermissions: {
            /** @enum {string} */
            role: "owner" | "member";
            canRead: boolean;
            canUpdate: boolean;
            canArchive: boolean;
            canRestore: boolean;
            canDelete: boolean;
        };
        /**
         * @description Normalized asset type (projected from media.type/mime_type).
         * @enum {string}
         */
        AssetType: "IMAGE" | "VIDEO" | "AUDIO" | "OTHER";
        /**
         * @description Projected from media.status/is_deleted (authority stays in media).
         * @enum {string}
         */
        AssetStatus: "PROCESSING" | "READY" | "FAILED" | "ARCHIVED";
        /**
         * @description Minimum provenance; full lineage graph is a later Studio concern.
         * @enum {string}
         */
        AssetOrigin: "UPLOAD" | "GENERATION" | "IMPORT" | "DERIVED";
        /** @description The stable, permanent reference to an asset. Canvas nodes and Studio contracts MUST store assetId (media.id) — never provider temporary URLs, signed URLs, base64 payloads, or storage credentials. */
        AssetRef: {
            assetId: string;
            workspaceId: string | null;
            projectId: string | null;
            ownerId: string | null;
            assetType: components["schemas"]["AssetType"];
            mimeType: string | null;
            status: components["schemas"]["AssetStatus"];
            /** @enum {string} */
            storageProvider: "oss" | "provider";
            width: number | null;
            height: number | null;
            durationMs: number | null;
            sizeBytes: number | null;
            title: string;
            /** @description Resolved preview URL (may be empty when storage is disabled). Not an identity. */
            url: string;
            /** @description Resolved thumbnail (image thumb / video snapshot). Empty until resolution available. */
            thumbnailUrl: string;
            origin: components["schemas"]["AssetOrigin"];
            /** Format: date-time */
            createdAt: string | null;
            /** Format: date-time */
            updatedAt: string | null;
        };
        AssetSummary: components["schemas"]["AssetRef"];
        AssetProvenanceSummary: {
            origin: components["schemas"]["AssetOrigin"];
            generationTaskId: string | null;
            generationBatchId: string | null;
            prompt: string | null;
            model: string | null;
        };
        AssetDetail: components["schemas"]["AssetRef"] & {
            ratio: string | null;
            tags: string[];
            isFavorite: boolean;
            ossUploaded: boolean;
            errorMessage: string | null;
            /** Format: date-time */
            failedAt: string | null;
            provenance: components["schemas"]["AssetProvenanceSummary"];
        };
        AssetListResponse: {
            projectId?: string | null;
            assets: components["schemas"]["AssetSummary"][];
            pagination: {
                limit: number;
                offset: number;
                total: number;
                hasMore: boolean;
            };
        };
        AssetDetailResponse: {
            asset: components["schemas"]["AssetDetail"];
        };
        /** @description Exactly one write mode: `url` present → provision a new asset; `assetId` present → re-scope an existing caller-owned asset. */
        AssetWriteRequest: {
            projectId: string;
            assetId?: string;
            /** @description Public http(s) source URL for a newly provisioned asset. */
            url?: string;
            title?: string;
            assetType?: components["schemas"]["AssetType"];
            mimeType?: string;
            width?: number;
            height?: number;
            durationMs?: number;
            sizeBytes?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description No session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description filter by workspace id */
                workspace?: string;
                /** @description filter by status */
                status?: "draft" | "active" | "archived";
                /** @description filter by project type */
                projectType?: "general" | "studio" | "short_drama";
                /** @description search by name or description */
                search?: string;
                /** @description page size */
                limit?: number;
                /** @description page offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Created project */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archiveProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restoreProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProjectAssets: {
        parameters: {
            query?: {
                /** @description filter by asset type */
                type?: "IMAGE" | "VIDEO" | "AUDIO" | "OTHER";
                /** @description filter by asset status */
                status?: "PROCESSING" | "READY" | "FAILED" | "ARCHIVED";
                /** @description search by title or prompt */
                search?: string;
                /** @description page size */
                limit?: number;
                /** @description page offset */
                offset?: number;
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project assets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMyAssets: {
        parameters: {
            query?: {
                type?: "IMAGE" | "VIDEO" | "AUDIO" | "OTHER";
                status?: "PROCESSING" | "READY" | "FAILED" | "ARCHIVED";
                search?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createOrRegisterAsset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssetWriteRequest"];
            };
        };
        responses: {
            /** @description Registered asset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailResponse"];
                };
            };
            /** @description Created asset */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset or project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
