'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {reserveBatchFunds,settleItemFunds}=require('./commercial-ledger.cjs');
function pg(rowsBy=[]){const calls=[];return{calls,async query(sql,p=[]){calls.push({sql,p});for(const [rx,result] of rowsBy)if(rx.test(sql))return result;if(/BEGIN|COMMIT|ROLLBACK/.test(sql))return{};return{rows:[],rowCount:1}}}}
test('reserve在同一事务扣真实余额、记reserve流水、创建每图V2 hold',async()=>{const d=pg([[/UPDATE users.*reward_credits/s,{rows:[],rowCount:1}],[/INSERT INTO credit_transactions/,{rows:[{id:1}],rowCount:1}]]);const r=await reserveBatchFunds(d,{userId:'u1',batchId:'b1',itemIds:['i1','i2'],amountPerItem:'50.0000',pool:'reward'});assert.equal(r.reserved,true);assert.match(d.calls[0].sql,/BEGIN/);assert.ok(d.calls.some(x=>/credit_transactions/.test(x.sql)&&x.p.includes('v2:b1:reserve')));assert.equal(d.calls.filter(x=>/generation_credit_holds_v2/.test(x.sql)).length,2);assert.match(d.calls.at(-1).sql,/COMMIT/)});
test('reserve同batch并发重试在advisory lock后命中流水，不再扣余额',async()=>{const d=pg([[/SELECT id FROM credit_transactions/,{rows:[{id:9}],rowCount:1}]]);const r=await reserveBatchFunds(d,{userId:'u1',batchId:'b1',itemIds:['i1'],amountPerItem:'50.0000',pool:'reward'});assert.equal(r.idempotent,true);assert.ok(d.calls.some(x=>/pg_advisory_xact_lock/.test(x.sql)));assert.equal(d.calls.some(x=>/UPDATE users/.test(x.sql)),false)});
test('reserve余额不足全事务rollback',async()=>{const d=pg([[/UPDATE users/,{rows:[],rowCount:0}]]);await assert.rejects(()=>reserveBatchFunds(d,{userId:'u',batchId:'b',itemIds:['i'],amountPerItem:'50.0000',pool:'recharge'}),/INSUFFICIENT/);assert.ok(d.calls.some(x=>/ROLLBACK/.test(x.sql)))});
test('settle commit仅将held转committed并插入唯一commit流水，不再扣余额',async()=>{const d=pg([[/UPDATE generation_credit_holds_v2/s,{rows:[{user_id:'u1',amount:'50',pool:'reward'}],rowCount:1}],[/INSERT INTO credit_transactions/,{rows:[{id:1}],rowCount:1}]]);const r=await settleItemFunds(d,{itemId:'i1',action:'commit'});assert.equal(r.changed,true);assert.equal(d.calls.some(x=>/UPDATE users/.test(x.sql)),false);assert.ok(d.calls.some(x=>x.p.includes('v2:i1:commit')))});
test('settle release将held转released、退款真实余额并记唯一流水',async()=>{const d=pg([[/UPDATE generation_credit_holds_v2/s,{rows:[{user_id:'u1',amount:'50',pool:'reward'}],rowCount:1}],[/UPDATE users/,{rows:[],rowCount:1}],[/INSERT INTO credit_transactions/,{rows:[{id:1}],rowCount:1}]]);const r=await settleItemFunds(d,{itemId:'i1',action:'release'});assert.equal(r.changed,true);assert.ok(d.calls.some(x=>/UPDATE users/.test(x.sql)));assert.ok(d.calls.some(x=>x.p.includes('v2:i1:release')))});
test('settle CAS未命中幂等返回，不重复流水退款',async()=>{const d=pg([[/UPDATE generation_credit_holds_v2/,{rows:[],rowCount:0}]]);const r=await settleItemFunds(d,{itemId:'i',action:'release'});assert.equal(r.changed,false);assert.equal(d.calls.some(x=>/credit_transactions/.test(x.sql)),false)});
